# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.create(username: "markymark", password: "abc123", points: 12121)
User.create(username: "habibti", password: "abc123", points: 5)

Mezze.create(name: "The Awful Falafel", calories: 652, price: 9.50, description: "mixed greens, vegetable kefta, turkish salad, spicy hummus, lemon mint carrots, chickpea salad, red cabbage slaw, pickled beets, tzatziki.", image: "https://mezeh.com/wp-content/uploads/2021/02/low_cal.png", vegetarian: true)
Mezze.create(name: "Oh Man, Lamb!", calories: 736, price: 11.99, description: "white rice, mixed greens, chicken shawarma, steak shawarma, turkish salad, lebanese tabbouleh, classic hummus, spicy feta dip, baba ganoush, chickpea salad, pickled turnips, tzatziki, harissa.",image: "https://mezeh.com/wp-content/uploads/2021/02/shawarma_dream.png", vegetarian: false)
Mezze.create(name: "Halal Pork (aka Chicken)", calories: 479, price: 10.25, description: "arugula, chicken kebab, couscous, classic hummus, winter roasted vegetables, baba ganoush, pickled beets, za’atar white bean, balsamic vinaigrette.", image: "https://mezeh.com/wp-content/uploads/2021/02/winter_classic.png", vegetarian: false)
Mezze.create(name: "Shawarma Karma", calories: 573, price: 11.75, description: "mixed greens, cauliflower rice pilaf, chicken shawarma, turkish salad, lebanese tabbouleh, spicy hummus, cilantro hummus, spicy feta dip, baba ganoush, greek beet dip, s’hug dip, pickled beets, pickled turnips, cilantro vinaigrette, tzatziki.",image: "https://mezeh.com/wp-content/uploads/2021/02/dip_crazy.png", vegetarian: false)
Mezze.create(name: "Eggplant Sabich Bowl", calories: 459, price: 11.15, description: "Crispy, golden eggplant cubes, and boiled egg served over a base of your choice: creamy hummus, turmeric pearl couscous, toasted cumin rice or romaine lettuce (or choose a combo of 2 bases). Comes with Israeli salad, pickled cabbage, tahini and amba sauce (pickled mango chutney).",image: "https://lh3.googleusercontent.com/M31P-rtautV7v3SKBAVe3Vu1VEpIIv0V_fd6JwioPeObNXM1aRXqyDbkx407tzIZULDwrn5F-IjPb1SSGY2T1ljeGz73PbYVv6nq7P_MqBtZJAqfXyngQ5WQnVXeyK74uWInkSLeQA2XSwoqen9hLqpX9lhlRAS4uVXUgqyi6XKvmYm6-P78iznCDOCYAcNB_MHCO13iuN9ePcfaWf9EVhap6wUeg9MG4N3eiBqj-AHKJdpUyLEtx29ZZYidYk34Ig5zwniIX11riZTluycw-kPydOH2rR-mbx4tNQmjHhqhxRElU9FufQhxEBnNXjpGqks8a3LHGTk8Hd13kjuF0L3xHG9o6ZhoW1X0Sr4pHzVYmHwHWcMgb8FUmWqrnY8I8VmSDQpxMnGkBOleDwxc7qVbmWNqy11fczcMCtVavqnzqkbesOJaDxObSZtex6xHD7ufMGVjMFjF2dWQd2XG56Va2_ixk7UOyEGlie4wirVMbP0_nlTpPa37uXrteG-NW5HDZpJiD50qDnrohFXmVbive99EkEMMmbvjUTXigsrv6F5pXmbtiJS86ejAc0ujtDCXPP-DIAs64m79gFzbhszo08cq0ghFM-1b9sQi4Sq2NtqaL71o_ZGfmZb4wgLD80fLi6qKzA4jZx9A-sLEqaOct8mkakBnjP7tG3787rNHIxEgo02hXoflamkZTA=s235-no?authuser=0", vegetarian: true)
Mezze.create(name: "Cauliflower Shawarma Bowl", calories: 524, price: 11.50, description: "Meet our meatless shawarma. Crispy, golden cauliflower tossed in Chef Einat's own shawarma spice blend. Comes with Israeli salad, pickled cabbage, pickled onions, tahini, amba sauce and chopped parsley.", image: "https://lh3.googleusercontent.com/XgBLeZHdom8yDWM2nFpB_WnKEY1dt5rHRb-GiiT3se0ccTS5RYurNdqYz6wL2mSyGtep3VwluEMqolwXsaO713JfG6Wx-b-_zbG-p_9nMgkbFy1a0aTdlfPtk893OKgoChBTQbK2iQATTpJV0H3G84R3CbsrvTK-X4PZoIgh3rQCNNsj27TLgeLSxS0aPHwV8vlHbz_09oKGptWiWT-NG9iA4JecVxGUZ4eF8Ch29PdvqXXSoEd7AS041NlMROXCap47-k-iuqzDQh9MZD5cf26Y8xvhY97oCRHfXfOvQ76I9JTWqsKaBbG6OdWX4fsJ0-bUIgT0hnX9g00VqEiHZ2jK5D_3eFNX7XCnFsliQ7AGqbJ6BgWntHrpkjBIdRzUP4alCMLJnEDTz-h4KzJ0Qy7Kz97b7YeUDbKW_TM6cRUqpnyT4jKFph98qMDO3NRwBjgsWvBm1VyRCDqc5UaaAxuszMcWsT_oEOZe5Og5hdB7s9Msc_3ErtF1FPIfDVXx5Tc3gsbibKF2IGijTqK3f8w8AGluH5e9koTimG9s41a-Ic5c-WQFgUtUb4KI_os8EB0M4-lkB95YzU9Axgxh9QwgBMPmaH_Ndd7zXTC4ZOTwPrLMSfHwGK0oYD4rHBp02vAOJhT4wR50PhSgI7xpZQZS5qImCTQ416lTDr6mQLyAzskiZTgXC3CR3w80PQ=s235-no?authuser=0", vegetarian: true)
Mezze.create(name: "Impossible Bowl", calories: 343, price: 10.15, description: "The Impossible Kebab is a vegan take on a classic Mediterranean kebab. The Impossible meat is mixed with fresh herbs, onions, and spices, and served over a base of your choice: creamy hummus, warm toasted cumin rice, turmeric pearl couscous or romaine lettuce.",image: "https://lh3.googleusercontent.com/xqrn8axgq2mEUw3fBsFu925lsAkN9Ewxkd_Xc-P8EvkvH2UBpgiISTBu5bFOKOzGBrEXftEh9-bG1BMRRisARQ46N9gh0PYHoVn_qTgKSlq-DwdvdbC92lDvJYq34hZbJ6vjQp9W4AVaWpflv29SvyWRwFYMQvJTId-9OL8aTSyE2wCkZTjPy9yiChDrDo6UjmlG_hwF25WZiMqWeppzmpiYp9S-iQsc5YqALTZUP5RA-D0mQGd-mucHllwCcU5yDqlQ9VJWY01kk-UaQ6-WApZzxgSezNr10sPOinKjpWUjvcO0zG9a9oXg0IeL2eEjNQzRlSRU2Ikke3ECEEAvnPkru3V2_xWEU_BZfdCX9Bq-F3MWlRou4YcHy2uzIf1hodFqa0KZkWsnOW7PBAUFhYBdS-ErlwdbvJv6tS5Asx_P1JEN8TSfMGqN7udoeBQvP2d7up6LX-iUQTxWLX7zLw6kABFIdPHYcsPIX1RbnbGp1SXwlAdyYl78FYFURO7oh_hzFAZub8kemXZC6sTrm7aLZHEb377NBejE3XazfjgM0rGnYKmAwBoFsngFZxb_bIDikRPk-sZ0vfpIUw9RTha3_51jbacjZ9_kYgRDdzCSlNhOwP6AcaJkw2Ha5UxYbDnaZyNG7hU70qYmpzXpmVruni6e5uCwdbUhTI4wFlbooOjMwTo4aUHs9jkmwQ=s235-no?authuser=0", vegetarian: true)
Mezze.create(name: "Beets & Carrots Bowl", calories: 310, price: 10.95, description: "Our marinated beets and Moroccan carrots served over a base of your choice: creamy hummus, turmeric pearl couscous, toasted cumin rice or romaine lettuce.",image: "https://lh3.googleusercontent.com/JEA8qtiyg_bABNd1W1bF0am0q605JUAY0eWk_VrcueLMc5LjFf-PEJMKoTNRFx6g3EYjVWmFxoehXbUgyLzpI4mj4zvUlobU6Kcahfhc6Yvc6xRpqSEgoLo6BDo2M8KAb6SCNY-dGg_I8U41smymYAH_4t3Bux9cQ1Bs7rEZQqDA8_6wnQREhkLRHXBmF_gak1cYFEvvSEkistQ2pWRXbnqczwChVpLQZBMdS12iF5iOab3HWdD1Gd-QsP6ikWFv8xaD099afdWbxXPR0RJFTeYl_vQCIZXUx6vmObc8kQU3Ur16noU5SitE4uI4vUlsP6JPCyJs-qLvKoFx-FE9YG4CA4RDoi_LMY6VhO3lg1e22he_5Hx-CpTzZTnyoOufuIwSQqKpJJDt3nmVyZs55DQsZMzjBhHe4lq8IO7Po1DmOUkVjvwPcKoiF7p2PLN0EvYK3EWTsm4e2hl6i1yJjVqq0GfgGclzY-5JZCHBWvUKS1KhbJpgNOa7Su3BsLrm75S3OFhBecf7xh4Auf3Gx3Sln4ymYVmxs4xt38C-MNKzk-TEnLoJ4mOKICrckT58zj1Q30LP3AcjzQRN_b1KLqe3UC3GOtcIVZ7ON7iC5zKB6KWXsEN_8tTNZmBPE7Qeuh3k8DDbSveuqyLTf0ekwmwZpZhlPrcb98vpGpwTggsIv7SblNXzy7tlirplEA=s235-no?authuser=0", vegetarian: true)

Order.create(user_id: 1, mezze_id: 1)
Order.create(user_id: 2, mezze_id: 3)


